export const getBookingsType = 'get/booking'
export const getBookingByIdType = 'getById/booking'
export const getBookingByBookingIdType = 'getByBookingId/booking'
export const bookingTicketByIdType = 'bookingTicket/booking'
export const payBookingByBookingIdType = 'payBooking/booking'
export const cancelBookingByBookingIdType = 'cancelBooking/booking'
